### ISSUE TITLE
服务挂了

### ISSUE THREAD

**Issue by WangNingkai** [georgezhao2010/fordpass_china#2]
获取车辆列表的接口挂了 `/api/dashboard/v1/users/vehicles`

**Comment by georgezhao2010** [comment]
> 
> 获取车辆列表的接口挂了 `/api/dashboard/v1/users/vehicles`

哈，现在才提起兴趣修改，由于福特中国多次修改API认证方式，目前已经恢复访问

**Comment by WangNingkai** [comment]
@georgezhao2010 感谢回复，请问如何获取refresh_token啊？
