### ISSUE TITLE
@georgezhao2010 关于如何获取refresh_token啊？

### ISSUE THREAD

**Issue by WangNingkai** [georgezhao2010/fordpass_china#3]
@georgezhao2010 首先感谢您的回复，无法通过账号登陆，请问要如何获取refresh_token呢？

_Originally posted by @WangNingkai in https://github.com/georgezhao2010/fordpass_china/issues/2#issuecomment-1159583559_

**Comment by georgezhao2010** [comment]
> 

发在这不好，马上我会在hassbian发个帖子

**Comment by georgezhao2010** [comment]
> @georgezhao2010 首先感谢您的回复，无法通过账号登陆，请问要如何获取refresh_token呢？
> 
> _Originally posted by @WangNingkai in [#2 (comment)](https://github.com/georgezhao2010/fordpass_china/issues/2#issuecomment-1159583559)_

发在这公开说不太好，马上我会在hassbian发个帖子

**Comment by WangNingkai** [comment]
@georgezhao2010 麻烦您贴个地址，非常感谢🙏

**Comment by georgezhao2010** [comment]
> @georgezhao2010 麻烦您贴个地址，非常感谢🙏

福特派App发公告定于26日停服更新，看看这次更新如果没有什么变化，就可以了
