### ISSUE TITLE
车锁信息如何写成switch状态？

### ISSUE THREAD

**Issue by williamxue80** [georgezhao2010/fordpass_china#6]
能否来一版车锁状态和发动机状态一致的？都是开关模式。

**Comment by georgezhao2010** [comment]
> 能否来一版车锁状态和发动机状态一致的？都是开关模式。

你非要开关，可以在HA用模板做一个出来。开关哪有锁好，还有locking和unlocking状态。这不好吗？

![Lock](https://github.com/georgezhao2010/lovelace-toggle-control-button/raw/main/lock-control.gif)
